name: Detect JS/TS Changes with File List

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      any_js_ts: ${{ steps.filter.outputs.any_js_ts }}
      js_ts_files: ${{ steps.filter.outputs.any_js_ts_files }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Detect JS/TS file changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          list-files: json
          filters: |
            any_js_ts:
              - '*.js'
              - '*.ts'
              - '*.tsx'

      - name: Debug Output
        run: |
          echo "JS/TS changed? ${{ steps.filter.outputs.any_js_ts }}"
          echo "Changed files: ${{ steps.filter.outputs.any_js_ts_files }}"

  run-js-ts-tasks:
    needs: detect-changes
    runs-on: ubuntu-latest
    if: needs.detect-changes.outputs.any_js_ts == 'true'
    steps:
      - name: Checkout Code Again
        uses: actions/checkout@v4

      - name: Process Changed JS/TS Files
        run: |
          echo "Processing JS/TS files:"
          echo "${{ needs.detect-changes.outputs.js_ts_files }}"
          # Here you could parse the JSON or loop through the file list
